class Tramite {
  final String idTramiteDetalle,
      nroExpediente,
      fecha,
      idTipoDocumento,
      tipoDocumento,
      nroDocumento,
      nroFolios,
      nombreOrigen,
      oficinaDestino,
      asunto,
      adjuntoOtros;

  Tramite(
      {this.idTramiteDetalle,
      this.nroExpediente,
      this.fecha,
      this.idTipoDocumento,
      this.tipoDocumento,
      this.nroDocumento,
      this.nroFolios,
      this.nombreOrigen,
      this.oficinaDestino,
      this.asunto,
      this.adjuntoOtros});

  factory Tramite.fromJson(Map<String, dynamic> json) {
    return Tramite(
      idTramiteDetalle: json["IdTramiteDetalle"],
      nroExpediente: json["NroExpediente"],
      fecha: json["Fecha"],
      idTipoDocumento: json["IdTipoDocumento"],
      tipoDocumento: json["TipoDocumento"],
      nroDocumento: json["NroDocumento"],
      nroFolios: json["NroFolios"],
      nombreOrigen: json["NombreOrigen"],
      adjuntoOtros: json["Adjunto_Otros"],
      oficinaDestino: json["OficinaDestino"],
      asunto: json["Asunto"],
    );
  }
}

// "IdTramiteDetalle": "3064907",
//         "NroExpediente": "4",
//         "Fecha": "2019-01-03 10:41:50",
//         "IdOrigen": null,
//         "IdDestino": "5",
//         "IdTipoDocumento": "11",
//         "NroDocumento": "83",
//         "Asunto": "FELICITA POR CARGO DE GOBERNADOR REGIONAL ",
//         "NroFolios": "1",
//         "Adjunto_Otros": "",
//         "Observaciones": "",
//         "Snip": "",
//         "Proceso": "",
//         "NombreOrigen": "CONGRESO REP.- YONHY LESCANO ANCIETA",
//         "TipoDocumento": "CARTA",
//         "Indice": "1.1",
//         "TipoOrigen": "OFICINA",
//         "TipoDestino": "OFICINA",
//         "IdTramite": "732117",
//         "UserNew": "23989605",
//         "DateNew": "2019-01-03 10:41:50",
//         "UserEdit": "23989605",
//         "DateEdit": "2019-01-03 10:41:50",
//         "Status": "A",
//         "OficinaDestino": "Mesa de Partes",
//         "EstadoTramite": "DERIVADO",
//         "PrimerHijo": "PRESREG",
//         "NroLibro": "4",
//         "IdRespuestaTramite": null,
//         "EsCopia": null,
//         "es_validado": null,
//         "NroDias": null,
//         "Anio": null,
//         "IdOficinaUsuaria": "5",
//         "clasificacion": "Trámite Normal",
//         "prioridad": "Normal",
//         "nroitem": null,
//         "estadomigracion": null,
//         "referencia": null
